name: azure-win-iis
on:
    push:
        branches:
            - main
permissions:
  id-token: write
  contents: read

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Workflow wired up ✅"